//! # Libraries
pub mod algebra;
pub mod algo;
pub mod convolution;
pub mod data_structure;
pub mod element;
pub mod enumerator;
pub mod flow;
pub mod geometry;
pub mod graph;
pub mod min_max_macro;
pub mod prelude;
pub mod range_traits;
pub mod string;
pub mod template;
pub mod util;
