pub mod addition;
pub mod bit_or_operation;
pub mod bit_xor_operation;
pub mod greatest_common_divisor;
pub mod greatest_common_divisor_naive;
pub mod maximization;
pub mod minimization;
pub mod multiplication;
pub mod overwrite_operation;
